In [4]:
import numpy as np
from datetime import datetime

In [5]:
x1=np.array([4,5,6,7,8],dtype='int64')
x2=np.array(['a','b','c','d','e'])
x3=np.array([True,False,False,True,True])
x4=np.array([1.2,3.4,6.8,9.1,5.6])
x5=np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

In [6]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)
print(x4.dtype)
print(x5.dtype)

int64
<U1
bool
float64
object


In [7]:
x1=x1.astype('int32')

In [8]:
x1

array([4, 5, 6, 7, 8], dtype=int32)

In [9]:
x1.dtype

dtype('int32')

In [10]:
x,y=np.unique(x2,return_inverse=True)

In [11]:
x

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [12]:
y

array([0, 1, 2, 3, 4])

In [13]:
x3=x3.astype('int32')

In [14]:
x3

array([1, 0, 0, 1, 1], dtype=int32)

In [15]:
x4.dtype

dtype('float64')

In [16]:
x4=x4.astype('float32')

In [ ]:
x4.dtype


dtype('float32')

In [18]:
x5=np.array([(i - datetime(1970, 1, 1)).days for i in x5], dtype='int32')


In [ ]:
from datetime import datetime
import numpy as np

x5 = np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

result = []
for i in x5:
    delta = i - datetime(1970, 1, 1)
    result.append([delta.days])

print(result)


[[18333], [18730], [19127], [19526], [20354]]


In [19]:
x5

array([18333, 18730, 19127, 19526, 20354], dtype=int32)

In [20]:
final_data=np.stack((x1,y,x3,x4,x5))

In [21]:
final_data

array([[4.00000000e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00,
        8.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
        4.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00],
       [1.20000005e+00, 3.40000010e+00, 6.80000019e+00, 9.10000038e+00,
        5.59999990e+00],
       [1.83330000e+04, 1.87300000e+04, 1.91270000e+04, 1.95260000e+04,
        2.03540000e+04]])

In [22]:
final_data.ndim

2