In [76]:
import numpy as np
from datetime import datetime

In [77]:
x1=np.array([4,5,6,7,8],dtype='int64')
x2=np.array(['a','b','c','d','e'])
x3=np.array([True,False,False,True,True])
x4=np.array([1.2,3.4,6.8,9.1,5.6])
x5=np.array([
    datetime(2020,3,12),
    datetime(2021,4,13),
    datetime(2022,5,15),
    datetime(2023,6,18),
    datetime(2025,9,23)
])

In [78]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)
print(x4.dtype)
print(x5.dtype)

int64
<U1
bool
float64
object


In [79]:
x1=x1.astype('int32')

In [80]:
x1

array([4, 5, 6, 7, 8], dtype=int32)

In [81]:
x1.dtype

dtype('int32')

In [83]:
x,y=np.unique(x2,return_inverse=True)

In [84]:
x

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [92]:
y

array([0, 1, 2, 3, 4])

In [86]:
x3=x3.astype('int32')

In [87]:
x3

array([1, 0, 0, 1, 1], dtype=int32)

In [88]:
x4.dtype

dtype('float64')

In [93]:
x4=x4.astype('float32')

In [94]:
x4.dtype

dtype('float32')

In [95]:
x5=np.array([(i - datetime(1970, 1, 1)).days for i in x5], dtype='int32')


In [96]:
x5

array([18333, 18730, 19127, 19526, 20354], dtype=int32)

In [99]:
final_data=np.stack((x1,y,x3,x4,x5))

In [100]:
final_data

array([[4.00000000e+00, 5.00000000e+00, 6.00000000e+00, 7.00000000e+00,
        8.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
        4.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        1.00000000e+00],
       [1.20000005e+00, 3.40000010e+00, 6.80000019e+00, 9.10000038e+00,
        5.59999990e+00],
       [1.83330000e+04, 1.87300000e+04, 1.91270000e+04, 1.95260000e+04,
        2.03540000e+04]])

In [102]:
final_data.ndim

2