# 1. Work on CSV data

In [2]:
import numpy as np

In [11]:
f1=np.genfromtxt("p1.csv",delimiter=",")

In [5]:
f1.dtype

dtype('float64')

In [12]:
f1

array([ 1.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
f2=np.genfromtxt("p2.csv",delimiter=",")

In [14]:
f2

array([[1., 3., 4., 5.],
       [3., 5., 8., 7.],
       [4., 5., 9., 0.]])

In [9]:
f2.dtype

dtype('float64')

In [15]:
f2=np.genfromtxt("p2.csv",delimiter=",")

In [23]:
f3=np.genfromtxt("p3.csv",delimiter=",",filling_values=0)

In [22]:
f3

array([[1., 3., 4., 5.],
       [3., 5., 5., 7.],
       [4., 5., 9., 0.]])

In [19]:
np.sum(f3,axis=0)

array([ 8.,  8., 13., 12.])

In [25]:
np.genfromtxt("p4.csv",delimiter=",",skip_header=1)

array([[1., 3., 4., 5.],
       [3., 5., 9., 7.],
       [4., 6., 9., 0.]])