# 1. Array create


In [1]:
import numpy as np

In [2]:
x1d=np.array([1,3,4,5])

In [3]:
x1d*8


array([ 8, 24, 32, 40])

In [4]:
x2d=np.array([[1,3,4,5],[9,8,2,3]])

In [5]:
x2d

array([[1, 3, 4, 5],
       [9, 8, 2, 3]])

In [6]:
x3d=np.array([[[2,3,4],[6,7,7],[3,4,4,]]])

In [7]:
x3d

array([[[2, 3, 4],
        [6, 7, 7],
        [3, 4, 4]]])

In [8]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2. Array attributes


In [13]:
arr=np.array([[2,3,4,5],[3,4,9,0]],dtype='int32')

In [14]:
arr

array([[2, 3, 4, 5],
       [3, 4, 9, 0]], dtype=int32)

In [15]:
arr.ndim

2

In [16]:
arr.shape

(2, 4)

In [17]:
arr.size

8

In [18]:
arr.dtype

dtype('int32')

# 3. operations

In [19]:
a1=np.array([2,3,5,6])
a2=np.array([8,7,9,4])

In [20]:
a1+a2

array([10, 10, 14, 10])

In [21]:
a1*a2

array([16, 21, 45, 24])

In [22]:
print(np.sum(a1))

16


In [102]:
print(np.mean(arr))

3.75


In [103]:
print(np.median(arr))

3.5


In [24]:
print(np.std(arr))

2.436698586202241


In [105]:
arr

array([[2, 3, 4, 5],
       [3, 4, 9, 0]], dtype=int32)

# 4. NumPy Copy vs View, Shape Manipulation, and Reshaping Arrays


In [26]:
a3=np.array([3,4,4,4,4,67,8,9])

In [27]:
a3

array([ 3,  4,  4,  4,  4, 67,  8,  9])

In [32]:
x

array([2, 3, 4, 6, 7, 9])

In [33]:
view_x=x[3:5]

In [34]:
view_x

array([6, 7])

In [35]:
x[4]=89

In [36]:
x

array([ 2,  3,  4,  6, 89,  9])

In [37]:
view_x

array([ 6, 89])

In [38]:
copy_view=x.copy()

In [39]:
copy_view

array([ 2,  3,  4,  6, 89,  9])

In [40]:
copy_view[3]=456

In [41]:
x

array([ 2,  3,  4,  6, 89,  9])

In [42]:
copy_view

array([  2,   3,   4, 456,  89,   9])

In [43]:
copy_view is x

False

In [44]:
x.T

array([ 2,  3,  4,  6, 89,  9])

In [45]:
x_2d=np.array([[3,4],[6,7]])

In [46]:
x_2d

array([[3, 4],
       [6, 7]])

In [47]:
x_2d.T

array([[3, 6],
       [4, 7]])

In [48]:
x

array([ 2,  3,  4,  6, 89,  9])

In [49]:
z=np.arange(1,7)

In [50]:
z

array([1, 2, 3, 4, 5, 6])

In [51]:
y=z.reshape(2,3)

In [52]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
T=y.flatten()


In [54]:
T

array([1, 2, 3, 4, 5, 6])

In [55]:
U=y.ravel()

In [56]:
U

array([1, 2, 3, 4, 5, 6])

In [57]:
T[3]=45

In [58]:
T

array([ 1,  2,  3, 45,  5,  6])

In [59]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
U[3]=78

In [61]:
U

array([ 1,  2,  3, 78,  5,  6])

In [62]:
y

array([[ 1,  2,  3],
       [78,  5,  6]])

# 5. NumPy Array Iteration, Joining, and Splitting 


In [63]:
e=np.arange(12)

In [64]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
e.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
for x in e:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [68]:
w=np.array([[3,4],[5,6],[7,8]])

In [69]:
for i in w:
    for j in i:
        print(j)

3
4
5
6
7
8


In [70]:
for i in np.nditer(w):
    print(i)

3
4
5
6
7
8


# 6. NumPy Searching, Sorting, and Filtering

In [107]:
arr = np.array([1, 3, 5, 7, 9])

# Find indices where values > 4
indices = np.where(arr > 4)
print(indices)# (array([2, 3, 4]),)

(array([2, 3, 4]),)


In [108]:
# Find exact matches
indices = np.where(arr == 5)# (array([2]),)# Find non-matches
indices = np.where(arr != 5)

In [109]:
sorted_arr = np.array([10, 20, 30, 40, 50])

# Find where 25 would be inserted
pos = np.searchsorted(sorted_arr, 25)# 2

In [112]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Multiple conditions (AND)
indices = np.where((arr > 2) & (arr < 5))# (array([2, 3]),)# Multiple conditions (OR)
indices1 = np.where((arr < 2) | (arr > 5))# (array([0, 5]),)

In [113]:
indices1

(array([0, 5]),)

In [114]:
# Return new sorted array
sorted_arr = np.sort(arr)# [1, 2, 3, 4, 5]# In-place sorting
arr.sort()# Modifies original array

In [115]:
arr_2d = np.array([[3, 1], [5, 2], [4, 0]])

# Sort each row
row_sorted = np.sort(arr_2d, axis=1)

# Sort each column
col_sorted = np.sort(arr_2d, axis=0)

# Sort by specific column (fancy indexing)
sorted_by_col1 = arr_2d[arr_2d[:,1].argsort()]

In [116]:
arr = np.array([10, 20, 30, 40, 50])

# Simple filter
filtered = arr[arr > 25]# [30, 40, 50]# Multiple conditions
filtered = arr[(arr > 15) & (arr < 45)]# [20, 30, 40]

In [117]:
condition = arr > 25
filtered = np.extract(condition, arr)# [30, 40, 50]

In [118]:
mask = np.array([True, False, True, False, True])
filtered = arr[mask]# [10, 30, 50]

In [119]:
filtered

array([10, 30, 50])

In [120]:
# Remove outliers
data = np.array([1, 2, 3, 100, 2, 3])
cleaned = data[(data > 0) & (data < 10)]

In [121]:
scores = np.array([85, 92, 88, 79, 95])
top_3 = np.sort(scores)[-3:]# [88, 92, 95]

In [123]:
scores

array([85, 92, 88, 79, 95])

# 5.1. NumPy Array Iteration, Joining, and Splitting 

In [71]:
a1=np.array([3,4,5])
a2=np.array([6,7,8])
a3=np.array(["a","b","c"])

In [72]:
np.concatenate((a1,a2))

array([3, 4, 5, 6, 7, 8])

In [73]:
a3

array(['a', 'b', 'c'], dtype='<U1')

In [74]:
np.concatenate((a1,a3))

array(['3', '4', '5', 'a', 'b', 'c'], dtype='<U21')

In [75]:
np.stack((a1,a2))

array([[3, 4, 5],
       [6, 7, 8]])

In [76]:
np.hstack((a1,a2))

array([3, 4, 5, 6, 7, 8])

In [77]:
np.vstack((a1,a2))

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
np.dstack((a1,a2))

array([[[3, 6],
        [4, 7],
        [5, 8]]])

In [79]:
yellow=np.ones((100,100))*255

In [80]:
yellow

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]], shape=(100, 100))

In [81]:
Black=np.zeros((100,100))

In [82]:
Black

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [83]:
White=np.zeros((100,100))

In [84]:
White

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [85]:
YBW=np.dstack((yellow,Black,White))

In [86]:
YBW

array([[[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        ...,
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.]],

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        ...,
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.]],

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        ...,
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.]],

       ...,

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        ...,
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.]],

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        ...,
        [255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,   0.,   0.]],

       [[255.,   0.,   0.],
        [255.,   0.,   0.],
        [255.,  

In [87]:
v=np.arange(12)

In [88]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
np.split(v,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [90]:
np.vsplit(YBW,100)

[array([[[255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.,   0.,   0.],
         [255.

In [91]:
np.hsplit(YBW,100)

[array([[[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        [[255.,   0.,   0.]],
 
        

In [92]:
data=np.random.rand(10,5)

In [93]:
train,test=np.split(data,[8])

In [94]:
train

array([[0.36679379, 0.00967659, 0.83060983, 0.26020147, 0.94741728],
       [0.70667989, 0.32272026, 0.70115966, 0.74622556, 0.80087161],
       [0.49354574, 0.65429023, 0.62346431, 0.16110817, 0.6122536 ],
       [0.15610263, 0.9222508 , 0.85506   , 0.60799165, 0.20303918],
       [0.11984074, 0.92857524, 0.84198736, 0.56878605, 0.14635964],
       [0.52743317, 0.52444455, 0.78201431, 0.94290121, 0.45683791],
       [0.77387087, 0.88222655, 0.4702492 , 0.14979381, 0.3412749 ],
       [0.72292046, 0.37104485, 0.45858296, 0.88014708, 0.34071395]])

In [95]:
test

array([[0.88468649, 0.21370604, 0.55161231, 0.88488947, 0.50801104],
       [0.55302759, 0.98497384, 0.66233832, 0.20296875, 0.52845041]])

In [96]:
np.random.randint(0,1000,size=(100,10))

array([[575, 989,  20, 203, 448, 310, 339, 229, 115, 713],
       [729, 944, 412,  80, 440, 387, 232, 989,  54, 828],
       [860, 972, 691, 651, 991, 157, 465, 205, 311, 426],
       [ 56, 925, 620, 449,  25, 987, 825, 405, 967, 955],
       [526, 227, 783, 188, 193, 544, 401, 105, 632, 304],
       [952, 197,  20, 480, 720, 231, 542, 910, 445, 587],
       [164, 796,  96, 461, 695, 634, 938, 834, 981, 204],
       [631, 268, 802, 419, 886, 792, 778, 182, 441, 646],
       [621, 652, 475, 615, 122, 596, 445, 769, 567,  21],
       [641, 653, 204, 286, 474, 870, 931, 363, 587, 173],
       [888, 665, 794, 328, 665, 143, 340, 222, 805, 926],
       [861, 389, 258, 748,  57, 696, 494, 462, 799, 300],
       [890, 268, 251, 973, 419, 199, 271, 314, 642, 396],
       [329, 936, 164, 894, 965, 279,  64, 987, 600, 162],
       [488, 553,  53, 426, 768, 996, 216,  69, 172, 952],
       [  9, 872, 944, 150, 367, 919, 562, 806, 648, 932],
       [746, 889, 833,  10, 870, 166, 959, 410, 287, 241

In [97]:
arr5=np.array([2,4,5,6,7,9,45])

In [98]:
arr5

array([ 2,  4,  5,  6,  7,  9, 45])

In [99]:
np.where(arr5>5)

(array([3, 4, 5, 6]),)

In [100]:
arr5[arr5>5]

array([ 6,  7,  9, 45])

In [101]:
np.sort(arr5)

array([ 2,  4,  5,  6,  7,  9, 45])