# 1. Array create


In [152]:
import numpy as np

In [153]:
x1d=np.array([1,3,4,5])

In [154]:
x1d

array([1, 3, 4, 5])

In [155]:
l=[3,4,5,6]

In [156]:
l*2

[3, 4, 5, 6, 3, 4, 5, 6]

In [157]:
x1d*8


array([ 8, 24, 32, 40])

In [158]:
x=[1,2,6,7,8]

In [159]:
np.array([2,4,6,8,9,0])

array([2, 4, 6, 8, 9, 0])

In [160]:
x2d=np.array([[1,3,4,5],[9,8,2,3]])

In [161]:
x2d

array([[1, 3, 4, 5],
       [9, 8, 2, 3]])

In [162]:
x2d

array([[1, 3, 4, 5],
       [9, 8, 2, 3]])

In [163]:
x3d=np.array([[[2,3,4,7],[6,7,7,0],[3,4,4,6]]])

In [164]:
x3d.shape

(1, 3, 4)

In [165]:
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [166]:
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [167]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [168]:
np.arange(0,10,2)  ## np.arange(start,end,step)

array([0, 2, 4, 6, 8])

In [169]:
np.linspace(0,100,5) ## np.linspace(start,end,equal_divider_value)

array([  0.,  25.,  50.,  75., 100.])

In [170]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2. Array attributes


In [171]:
arr=np.array([[2,3,4,5],[3,4,9,0]],dtype='int32')

In [172]:
arr

array([[2, 3, 4, 5],
       [3, 4, 9, 0]], dtype=int32)

In [173]:
arr.ndim

2

In [174]:
arr.shape

(2, 4)

In [175]:
arr.size

8

In [176]:
arr.dtype

dtype('int32')

# 3. operations

In [177]:
a1=np.array([2,3,5,6])
a2=np.array([8,7,9,4])

In [178]:
l=[4,"hello",8,9]

In [179]:
type(l)

list

In [180]:
a3=np.array(l)

In [181]:
a3

array(['4', 'hello', '8', '9'], dtype='<U21')

In [182]:
l1=[2,3,5]
a1=np.array(l1)
l2=[5,6,9]
a2=np.array(l2)
l1+l2
print(a1+a2)

[ 7  9 14]


In [183]:
a1+a2

array([ 7,  9, 14])

In [184]:
a1*a2

array([10, 18, 45])

In [185]:
a1

array([2, 3, 5])

In [186]:
print(np.sum(a1))
print(np.average(a1))

10
3.3333333333333335


In [187]:
print(np.mean(arr))

3.75


In [188]:
print(np.median(arr))

3.5


In [189]:
print(np.std(arr))

2.436698586202241


In [190]:
arr2=np.array([2,2,2,4,5,7,7,7,7,7,7])

In [191]:
from scipy import stats
scipy.stats.mode(arr2)

ModeResult(mode=np.int64(7), count=np.int64(6))

In [192]:
arr

array([[2, 3, 4, 5],
       [3, 4, 9, 0]], dtype=int32)

# 4. NumPy Copy vs View, Shape Manipulation, and Reshaping Arrays


In [286]:
a3=np.array([3,4,4,4,4,67,8,9])

In [287]:
a3

array([ 3,  4,  4,  4,  4, 67,  8,  9])

In [301]:
x=[1,2,6,7,8]

In [302]:
x

[1, 2, 6, 7, 8]

In [308]:
view_x=x[3:5]

In [309]:
view_x

[7, 89]

In [305]:
x[4]=89

In [311]:
x

[1, 2, 6, 7, 89]

In [312]:
view_x

[7, 89]

In [323]:
copy_view=x.copy()
copy_view1=x.copy()
copy_view2=x.copy()

In [324]:
print(copy_view)
print(copy_view1)
print(copy_view2)
print(x)

[1, 2, 6, 7, 89]
[1, 2, 6, 7, 89]
[1, 2, 6, 7, 89]
[1, 2, 6, 7, 89]


In [317]:
copy_view[3]=456

In [321]:
copy_view

[1, 2, 6, 456, 89]

In [322]:
x

[1, 2, 6, 7, 89]

In [205]:
copy_view

[1, 2, 6, 456, 89]

In [206]:
copy_view is x

False

In [207]:
x=np.array([2,4,6])

In [208]:
x.T

array([2, 4, 6])

In [325]:
x_2d=np.array([[3,4],[6,7]])

In [326]:
x_2d

array([[3, 4],
       [6, 7]])

In [327]:
x_2d.T

array([[3, 6],
       [4, 7]])

In [328]:
x

[1, 2, 6, 7, 89]

In [387]:
z=np.arange(1,101)

In [388]:
z

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [391]:
y=z.reshape(4,-1)

In [392]:
y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [362]:
T=y.flatten()


In [363]:
T

array([ 1,  2,  3, 78,  5,  6])

In [350]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [353]:
U=y.ravel()

In [354]:
U

array([1, 2, 3, 4, 5, 6])

In [355]:
T[3]=45

In [356]:
T

array([ 1,  2,  3, 45,  5,  6])

In [357]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [358]:
U[3]=78

In [359]:
U

array([ 1,  2,  3, 78,  5,  6])

In [360]:
y

array([[ 1,  2,  3],
       [78,  5,  6]])

# 5. NumPy Array Iteration, Joining, and Splitting 


In [393]:
e=np.arange(12)

In [394]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [395]:
e.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [396]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [400]:
for i in e:
    print(i,end=',')

0,1,2,3,4,5,6,7,8,9,10,11,

In [402]:
w=np.array([[3,4],[5,6],[7,8]])


In [233]:
for i in w:
    for j in i: 
       print(j)

3
4
5
6
7
8


In [234]:
for i in np.nditer(w):
    print(i)

3
4
5
6
7
8


# 6. NumPy Searching, Sorting, and Filtering

In [411]:
arr = np.array([1, 3, 5, 7, 9])
indices = np.where(arr > 4)
print(indices)
print(arr[2],arr[3],arr[4])

(array([2, 3, 4]),)
5 7 9


In [236]:

indices = np.where(arr == 5)
indices = np.where(arr != 5)

In [423]:
sorted_arr = np.array([10, 20, 30, 40, 50])
ritik = np.searchsorted(sorted_arr, 11)# 2

In [424]:
ritik

np.int64(1)

In [417]:
sorted_arr

array([10, 20, 30, 40, 50])

In [418]:
pos

np.int64(3)

In [238]:
arr = np.array([1, 2, 3, 4, 5, 6])
indices = np.where((arr > 2) & (arr < 5))# (array([2, 3]),)# Multiple conditions (OR)
indices1 = np.where((arr < 2) | (arr > 5))# (array([0, 5]),)

In [239]:
indices1

(array([0, 5]),)

In [240]:
# Return new sorted array
sorted_arr = np.sort(arr)# [1, 2, 3, 4, 5]# In-place sorting
arr.sort()# Modifies original array

In [241]:
arr_2d = np.array([[3, 1], [5, 2], [4, 0]])

# Sort each row
row_sorted = np.sort(arr_2d, axis=1)

# Sort each column
col_sorted = np.sort(arr_2d, axis=0)

# Sort by specific column (fancy indexing)
sorted_by_col1 = arr_2d[arr_2d[:,1].argsort()]

In [242]:
arr = np.array([10, 20, 30, 40, 50])

# Simple filter
filtered = arr[arr > 25]# [30, 40, 50]# Multiple conditions
filtered = arr[(arr > 15) & (arr < 45)]# [20, 30, 40]

In [243]:
condition = arr > 25
filtered = np.extract(condition, arr)# [30, 40, 50]

In [244]:
mask = np.array([True, False, True, False, True])
filtered = arr[mask]# [10, 30, 50]

In [245]:
filtered

array([10, 30, 50])

In [246]:
# Remove outliers
data = np.array([1, 2, 3, 100, 2, 3])
cleaned = data[(data > 0) & (data < 10)]

In [247]:
scores = np.array([85, 92, 88, 79, 95])
top_3 = np.sort(scores)[-3:]# [88, 92, 95]

In [248]:
scores

array([85, 92, 88, 79, 95])

# 5.1. NumPy Array Iteration, Joining, and Splitting 

In [428]:
a1=np.array([3,4,5])
a2=np.array([6,7,8])
a3=np.array(["a","b","c"])

In [429]:
np.concatenate((a1,a2))

array([3, 4, 5, 6, 7, 8])

In [430]:
a3

array(['a', 'b', 'c'], dtype='<U1')

In [431]:
np.concatenate((a1,a3))

array(['3', '4', '5', 'a', 'b', 'c'], dtype='<U21')

In [441]:
c1=np.array([2,3,5,6,9])
c2=np.array([6,7,9,4,7])
c3=np.array([4,5,2,1,9])

In [442]:
np.stack((c1,c2,c3))

array([[2, 3, 5, 6, 9],
       [6, 7, 9, 4, 7],
       [4, 5, 2, 1, 9]])

In [444]:
np.vstack((c1,c2,c3))

array([[2, 3, 5, 6, 9],
       [6, 7, 9, 4, 7],
       [4, 5, 2, 1, 9]])

In [445]:
np.hstack((c1,c2,c3))

array([2, 3, 5, 6, 9, 6, 7, 9, 4, 7, 4, 5, 2, 1, 9])

In [446]:
np.dstack((c1,c2,c3))

array([[[2, 6, 4],
        [3, 7, 5],
        [5, 9, 2],
        [6, 4, 1],
        [9, 7, 9]]])

In [253]:
np.stack((a1,a2))

array([[3, 4, 5],
       [6, 7, 8]])

In [443]:
np.hstack((a1,a2))

array([3, 4, 5, 6, 7, 8])

In [255]:
np.vstack((a1,a2))

array([[3, 4, 5],
       [6, 7, 8]])

In [256]:
np.dstack((a1,a2))

array([[[3, 6],
        [4, 7],
        [5, 8]]])

In [449]:
yellow=np.ones((100,100))*255

In [258]:
yellow

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]], shape=(100, 100))

In [450]:
Black=np.zeros((100,100))

In [451]:
Black

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [452]:
White=np.zeros((100,100))

In [262]:
White

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 100))

In [263]:
YBW=np.dstack((yellow,Black,White))

In [ ]:
YBW

In [453]:
v=np.arange(12)

In [454]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [455]:
np.split(v,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [460]:
x=np.vsplit(YBW,100)

In [269]:
x=np.hsplit(YBW,100)

In [ ]:
x

In [ ]:
data=np.random.rand(1,100,10)  ## np.random.rand(start,end,count_of_columns)

In [476]:
np.random.randint(1,100)

15

In [471]:
data

array([[[9.08701309e-01, 1.12011148e-03, 5.56181735e-01, 7.56635804e-01,
         2.58688331e-01, 1.93132865e-01, 8.40982245e-02, 3.26433577e-01,
         5.59844312e-01, 1.15843857e-01],
        [3.76695362e-01, 9.07240465e-03, 8.18679420e-01, 1.28448718e-01,
         2.83342948e-01, 1.84277187e-02, 4.32240784e-01, 8.40121503e-01,
         3.92151211e-01, 1.79497323e-01],
        [7.53698834e-01, 7.88806982e-01, 1.73753475e-01, 7.70854109e-01,
         9.47297888e-01, 1.66377587e-01, 7.70984293e-01, 7.08572005e-01,
         4.73573888e-01, 5.79204606e-02],
        [7.46944178e-02, 8.52414659e-01, 9.90148373e-01, 6.76052257e-01,
         4.45958307e-01, 6.47573643e-01, 5.94395859e-01, 3.83612260e-01,
         6.56261446e-02, 8.21512947e-01],
        [3.71833529e-01, 8.18785643e-01, 2.52508750e-01, 1.02947985e-03,
         1.58938283e-01, 4.68539417e-01, 9.44303635e-01, 1.02193620e-01,
         8.54209774e-01, 5.27024096e-01],
        [8.25920766e-01, 2.98374431e-01, 8.39947165e-01, 7.7

In [271]:
train,test=np.split(data,[8])

In [272]:
train

array([[7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01,
        7.06630522e-03],
       [2.30624250e-02, 5.24774660e-01, 3.99860972e-01, 4.66656632e-02,
        9.73755519e-01],
       [2.32771340e-01, 9.06064345e-02, 6.18386009e-01, 3.82461991e-01,
        9.83230886e-01],
       [4.66762893e-01, 8.59940407e-01, 6.80307539e-01, 4.50499252e-01,
        1.32649612e-02],
       [9.42201756e-01, 5.63288218e-01, 3.85416503e-01, 1.59662522e-02,
        2.30893826e-01],
       [2.41025466e-01, 6.83263519e-01, 6.09996658e-01, 8.33194912e-01,
        1.73364654e-01],
       [3.91060608e-01, 1.82236088e-01, 7.55361410e-01, 4.25155874e-01,
        2.07941663e-01],
       [5.67700328e-01, 3.13132925e-02, 8.42284775e-01, 4.49754133e-01,
        3.95150236e-01]])

In [273]:
test

array([[0.92665887, 0.727272  , 0.32654077, 0.57044397, 0.52083426],
       [0.96117202, 0.84453385, 0.74732011, 0.53969213, 0.58675117]])

In [274]:
b=np.random.randint(0,1000,size=(100,10))

In [275]:
np.random.seed(42)
a=np.random.randint(0,100,20)

In [276]:
a

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37], dtype=int32)

In [277]:
arr5=np.array([2,4,5,6,7,9,45])

In [278]:
arr5

array([ 2,  4,  5,  6,  7,  9, 45])

In [279]:
np.where(arr5>4)

(array([2, 3, 4, 5, 6]),)

In [280]:
arr5[arr5>5]

array([ 6,  7,  9, 45])

In [281]:
np.sort(arr5)

array([ 2,  4,  5,  6,  7,  9, 45])